# Generated by Django 6.0.3 on 2026-04-12 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('documents', '0002_document_ocr_text_document_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='doc_date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='ocr_text',
        ),
        migrations.AlterField(
            model_name='document',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='document',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='company.company'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На проверке'), ('approved', 'Одобрен')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
