# Generated by Django 6.0.3 on 2026-04-12 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('documents', '0003_remove_document_doc_date_remove_document_ocr_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='company.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На проверке'), ('approved', 'Одобрен')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
