# Generated by Django 6.0.3 on 2026-05-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_new_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает обработки'), ('ready', 'Одобрен'), ('duplicate', 'Дубликат'), ('needs_verification', 'Требует проверки'), ('needs_approval', 'Ожидает одобрения')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
